import puppeteer from "puppeteer";

export const generateCVPdf = async (cvData) => {
  const {
    fullName,
    contactInfo,
    summary,
    experience,
    skills,
    education,
    achievements,
    projects,
    tone = "balanced",
    branding = {},
  } = cvData;

  const html = buildCVHtml({
    fullName,
    contactInfo,
    summary,
    experience,
    skills,
    education,
    achievements,
    projects,
    tone,
    branding,
  });

  const browser = await puppeteer.launch({
    headless: "new",
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdf = await page.pdf({
      format: "A4",
      margin: {
        top: "14mm",
        right: "16mm",
        bottom: "14mm",
        left: "16mm",
      },
      printBackground: true,
    });

    return pdf;
  } finally {
    await browser.close();
  }
};

// ─── Cover Letter PDF ──────────────────────────────────────
export const generateCoverLetterPdf = async ({ fullName, jobTitle, company, tone, content }) => {
  const accentColor = tone === "bold" ? "#1a1a2e" : "#033876";
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #1f2937; margin: 0; padding: 0; font-size: 11pt; line-height: 1.8; }
    .header { background: ${accentColor}; color: white; padding: 28px 36px 22px; }
    .header h1 { margin: 0 0 4px; font-size: 18pt; font-weight: 700; letter-spacing: -0.3px; }
    .header p { margin: 0; font-size: 9pt; opacity: 0.75; }
    .meta { background: #f9fafb; border-bottom: 1px solid #e5e7eb; padding: 12px 36px; font-size: 9pt; color: #6b7280; display: flex; justify-content: space-between; }
    .body { padding: 30px 36px; }
    .body p { margin: 0 0 14px; }
    .footer { padding: 16px 36px; border-top: 1px solid #e5e7eb; font-size: 8.5pt; color: #9ca3af; text-align: center; }
  </style></head><body>
  <div class="header"><h1>${fullName || "Applicant"}</h1><p>Cover Letter</p></div>
  <div class="meta"><span>${jobTitle || "Position"} — ${company || "Company"}</span><span>${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</span></div>
  <div class="body">${(content || "").split("\n\n").map(p => `<p>${p.replace(/\n/g, "<br>")}</p>`).join("")}</div>
  <div class="footer">Generated by Seevv · seevv.io</div>
  </body></html>`;

  const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox", "--disable-setuid-sandbox"] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    return await page.pdf({ format: "A4", margin: { top: "0", right: "0", bottom: "0", left: "0" }, printBackground: true });
  } finally { await browser.close(); }
};

// ─── Proof of Work PDF ─────────────────────────────────────
export const generateProofOfWorkPdf = async ({ fullName, evidence }) => {
  const rows = (evidence || []).map((item, i) => `
    <tr style="background:${i % 2 === 0 ? "#f9fafb" : "white"}">
      <td style="padding:10px 14px;font-size:9.5pt;color:#1f2937;border-bottom:1px solid #f3f4f6;vertical-align:top;font-weight:600">${item.claim || ""}</td>
      <td style="padding:10px 14px;font-size:9pt;color:#4b5563;border-bottom:1px solid #f3f4f6;vertical-align:top">${item.proof_type || "—"}</td>
      <td style="padding:10px 14px;font-size:8.5pt;color:#033876;border-bottom:1px solid #f3f4f6;vertical-align:top;word-break:break-all">${item.proof_url ? `<a href="${item.proof_url}">${item.proof_url}</a>` : "—"}</td>
      <td style="padding:10px 14px;font-size:8.5pt;color:#6b7280;border-bottom:1px solid #f3f4f6;vertical-align:top">${item.proof_notes || "—"}</td>
    </tr>`).join("");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
  <style>
    body { font-family: -apple-system, Arial, sans-serif; color: #1f2937; margin: 0; padding: 0; }
    .header { background: #033876; color: white; padding: 26px 32px 20px; }
    .header h1 { margin: 0 0 3px; font-size: 17pt; font-weight: 700; }
    .header p { margin: 0; font-size: 9pt; opacity: 0.7; }
    table { width: 100%; border-collapse: collapse; margin: 0; }
    thead th { background: #1e3a5f; color: white; padding: 10px 14px; font-size: 8.5pt; text-align: left; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; }
    .footer { padding: 14px 32px; border-top: 1px solid #e5e7eb; font-size: 8pt; color: #9ca3af; text-align: center; }
  </style></head><body>
  <div class="header"><h1>${fullName || "Applicant"}</h1><p>Proof of Work · Evidence Library · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p></div>
  <table>
    <thead><tr><th style="width:35%">Claim</th><th style="width:13%">Type</th><th style="width:30%">Link</th><th style="width:22%">Notes</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="4" style="text-align:center;padding:20px;color:#9ca3af">No evidence added yet</td></tr>'}</tbody>
  </table>
  <div class="footer">Generated by Seevv · seevv.io</div>
  </body></html>`;

  const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox", "--disable-setuid-sandbox"] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    return await page.pdf({ format: "A4", margin: { top: "0", right: "0", bottom: "0", left: "0" }, printBackground: true });
  } finally { await browser.close(); }
};

const buildCVHtml = ({
  fullName,
  contactInfo,
  summary,
  experience,
  skills,
  education,
  achievements,
  projects,
  tone,
  branding = {},
}) => {
  const accentColor = branding.accentColor || (tone === "bold" ? "#1a1a2e" : "#033876");
  const fontMap = { professional: "Arial, sans-serif", elegant: "Georgia, serif", modern: "'Trebuchet MS', sans-serif" };
  const fontFamily = fontMap[branding.fontStyle] || fontMap.professional;
  const headerStyle = branding.headerStyle || "classic";

  // ── Strip name from contact info ───────────────────
  const cleanContactInfo = (() => {
    if (!contactInfo) return "";

    const nameLower = (fullName || "").trim().toLowerCase();
    const nameParts = nameLower.split(/\s+/).filter(Boolean);

    return contactInfo
      .split("\n")
      .filter((line) => {
        const lineLower = line.trim().toLowerCase();
        if (!lineLower) return false;
        if (lineLower === nameLower) return false;

        const lineWords = lineLower
          .replace(/[^a-z\s]/g, "")
          .trim()
          .split(/\s+/)
          .filter(Boolean);

        if (lineWords.length >= 2) {
          const allAreNameParts = lineWords.every((word) =>
            nameParts.some(
              (part) =>
                part === word || part.includes(word) || word.includes(part),
            ),
          );
          if (allAreNameParts) return false;
        }

        return true;
      })
      .join("\n")
      .trim();
  })();

  // ── Experience HTML ─────────────────────────────────
  const experienceHtml = (experience || [])
    .map(
      (role) => `
      <div class="role">
        <div class="role-header">
          <div class="role-left">
            <p class="role-title">${escapeHtml(role.title || "")}</p>
            ${
              role.company
                ? `<p class="role-company">${escapeHtml(role.company)}${
                    role.period
                      ? ` <span class="role-period-inline">· ${escapeHtml(role.period)}</span>`
                      : ""
                  }</p>`
                : role.period
                  ? `<p class="role-company"><span class="role-period-inline">${escapeHtml(role.period)}</span></p>`
                  : ""
            }
          </div>
        </div>
        <ul class="bullets">
          ${(role.bullets || [])
            .map((b) => `<li>${escapeHtml(b)}</li>`)
            .join("")}
        </ul>
      </div>
    `,
    )
    .join("");

  const skillsHtml = (skills || [])
    .map((s) => `<li>${escapeHtml(s)}</li>`)
    .join("");

  const educationHtml = (education || [])
    .map((e) => `<li>${escapeHtml(e)}</li>`)
    .join("");

  const achievementsHtml =
    achievements && achievements.length > 0
      ? `
      <div class="section">
        <h2 class="section-title">Achievements</h2>
        <ul class="bullets">
          ${achievements.map((a) => `<li>${escapeHtml(a)}</li>`).join("")}
        </ul>
      </div>
    `
      : "";

  const projectsHtml =
    projects && projects.length > 0
      ? `
      <div class="section">
        <h2 class="section-title">Projects</h2>
        <ul class="bullets">
          ${projects.map((p) => `<li>${escapeHtml(p)}</li>`).join("")}
        </ul>
      </div>
    `
      : "";

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(fullName || "CV")} — CV</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: ${fontFamily};
      font-size: 9.5pt;
      line-height: 1.4;
      color: #1a1a1a;
      background: #ffffff;
    }

    .page {
      max-width: 100%;
    }

    /* ── Header ── */
    .header {
      text-align: center;
      margin-bottom: 8px;
      padding-bottom: 8px;
      border-bottom: 2px solid ${accentColor};
    }

    .name {
      font-size: 18pt;
      font-weight: 700;
      color: ${accentColor};
      letter-spacing: 0.5px;
      margin-bottom: 2px;
    }

    .contact {
      font-size: 8pt;
      color: #555;
      line-height: 1.4;
      white-space: pre-line;
    }

    /* ── Sections ── */
    .section {
      margin-bottom: 7px;
    }

    .section-title {
      font-size: 9pt;
      font-weight: 700;
      color: ${accentColor};
      text-transform: uppercase;
      letter-spacing: 1px;
      border-bottom: 1px solid ${accentColor};
      padding-bottom: 1px;
      margin-bottom: 5px;
    }

    /* ── Summary ── */
    .summary-text {
      font-size: 9.5pt;
      line-height: 1.45;
      color: #333;
      text-align: justify;
    }

    /* ── Experience ── */
    .role {
      margin-bottom: 8px;
    }

    .role:last-child {
      margin-bottom: 0;
    }

    .role-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 2px;
    }

    .role-left {
      flex: 1;
    }

    .role-title {
      font-size: 9.5pt;
      font-weight: 700;
      color: #1a1a1a;
    }

    .role-company {
      font-size: 8.5pt;
      color: #555;
      font-style: italic;
      margin-top: 1px;
    }

    .role-period-inline {
      font-style: normal;
      color: #777;
      font-size: 8pt;
    }

    /* ── Bullets ── */
    .bullets {
      margin-left: 12px;
      margin-top: 2px;
    }

    .bullets li {
      font-size: 9pt;
      line-height: 1.4;
      color: #333;
      margin-bottom: 1px;
    }

    /* ── Skills ── */
    .skills-list {
      list-style: none;
      margin: 0;
      padding: 0;
    }

    .skills-list li {
      font-size: 9pt;
      line-height: 1.4;
      color: #333;
      margin-bottom: 1px;
    }

    .skills-list li::before {
      content: "● ";
      color: ${accentColor};
      font-size: 7pt;
    }

    /* ── Education ── */
    .education-list {
      list-style: none;
      margin: 0;
      padding: 0;
    }

    .education-list li {
      font-size: 9pt;
      line-height: 1.4;
      color: #333;
      margin-bottom: 1px;
    }

    .education-list li::before {
      content: "● ";
      color: ${accentColor};
      font-size: 7pt;
    }

    /* ── Page break control ── */
    .section {
      break-inside: auto;
      page-break-inside: auto;
    }

    .role {
      page-break-inside: avoid;
      break-inside: avoid;
    }
  </style>
</head>
<body>
  <div class="page">

    <!-- Header -->
    ${headerStyle === "modern" ? `
    <div style="border-left:5px solid ${accentColor};padding:8px 12px;margin-bottom:10px;background:#f9fafb;">
      <p style="font-size:18pt;font-weight:700;color:${accentColor};letter-spacing:0.5px;margin-bottom:2px;">${escapeHtml(fullName || "Your Name")}</p>
      ${cleanContactInfo ? `<p style="font-size:8pt;color:#555;line-height:1.4;">${escapeHtml(cleanContactInfo)}</p>` : ""}
    </div>` : headerStyle === "minimal" ? `
    <div style="padding-bottom:6px;margin-bottom:8px;border-bottom:2px solid ${accentColor};">
      <p style="font-size:18pt;font-weight:700;color:#111;letter-spacing:0.5px;margin-bottom:2px;">${escapeHtml(fullName || "Your Name")}</p>
      ${cleanContactInfo ? `<p style="font-size:8pt;color:#555;line-height:1.4;">${escapeHtml(cleanContactInfo)}</p>` : ""}
    </div>` : `
    <div class="header">
      <p class="name">${escapeHtml(fullName || "Your Name")}</p>
      ${cleanContactInfo ? `<p class="contact">${escapeHtml(cleanContactInfo)}</p>` : ""}
    </div>`}

    <!-- Summary -->
    ${
      summary
        ? `
      <div class="section">
        <h2 class="section-title">Summary</h2>
        <p class="summary-text">${escapeHtml(summary.trim())}</p>
      </div>
    `
        : ""
    }

    <!-- Experience -->
    ${
      experience && experience.length > 0
        ? `
      <div class="section">
        <h2 class="section-title">Experience</h2>
        ${experienceHtml}
      </div>
    `
        : ""
    }

    <!-- Skills -->
    ${
      skills && skills.length > 0
        ? `
      <div class="section">
        <h2 class="section-title">Core Skills &amp; Technologies</h2>
        <ul class="skills-list">
          ${skillsHtml}
        </ul>
      </div>
    `
        : ""
    }

    <!-- Achievements -->
    ${achievementsHtml}

    <!-- Projects -->
    ${projectsHtml}

    <!-- Education -->
    ${
      education && education.length > 0
        ? `
      <div class="section">
        <h2 class="section-title">Education</h2>
        <ul class="education-list">
          ${educationHtml}
        </ul>
      </div>
    `
        : ""
    }

  </div>
</body>
</html>
  `;
};

// ─── HTML escape helper ───────────────────────────────────

const escapeHtml = (text) => {
  if (!text) return "";
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
};
