services:
  - type: web
    name: seevv-server
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22"
